package com.vinilearning.eventmanager.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENTS.
 */
public class Students {

    private Long id;
    /** Not-null value. */
    private String name;
    private String gioitinh;
    private String diachi;

    public Students() {
    }

    public Students(Long id) {
        this.id = id;
    }

    public Students(Long id, String name, String gioitinh, String diachi) {
        this.id = id;
        this.name = name;
        this.gioitinh = gioitinh;
        this.diachi = diachi;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getGioitinh() {
        return gioitinh;
    }

    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }

    public String getDiachi() {
        return diachi;
    }

    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

}
